mozilla/stubattribution-tests

tests/test_stub_attribution_organic.py
tests/test_stub_attribution_search.py
tox.ini

@davehunt r?  Still working on getting these running in Sauce Labs, but they're ready for an initial review/more help; thanks!

Fix Flake8 and add pytest, etc.

---

Jenkinsfile

Due to changes in Pipeline Model Definition/related plugins
@davehunt r?

Pass 'xterm' in to ansiColor()

---

Jenkinsfile

@davehunt r?
Adhoc: https://fx-test-jenkins-dev.stage.mozaws.net:8443/view/Web/job/stubattribution.adhoc/13/console

Restore original PYTEST_ADDOPTS formatting

---

Jenkinsfile

@davehunt r?
Ad-hoc: https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/stubattribution.adhoc/85/console

Switch to libraries declaration

---

requirements/tests.txt

Passing ad-hoc: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/stubattribution.adhoc/29/

Pin Selenium client to v3.6.0 to avoid issues with Google Chrome and Sauce Labs

---

tox.ini

Pass along Git env variables to ActiveData

---

Jenkinsfile
tox.ini

Simplify Sauce Labs credential configs

---

Jenkinsfile

Set number of pytest processes via environment variable

---

.dockerignore
.gitignore
Dockerfile
Jenkinsfile

Passing ad-hoc job here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/stubattribution.adhoc/130/console
@davehunt r?

Upgrade to fxtest-jenkins-pipeline library v1.10

---

Dockerfile
Jenkinsfile

@davehunt r?
Ad-hoc here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/stubattribution.adhoc/136/console

IRC openssl removal

---

requirements.txt

Reverts mozilla/stubattribution-tests#101

Revert "Update querystringsafe_base64 to 1.1.1"

---

Pipfile
Pipfile.lock

Passing ad-hoc build here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/stubattribution.adhoc/168/console
Also note https://github.com/pypa/pipenv/issues/1386 for more context

Tweak for Pep 503

---

Pipfile
Pipfile.lock

@jrbenny35 @rbillings @rpappalax r?

Bump selenium to 3.9.0

---

Jenkinsfile

Really make cron job hourly

---

.pyup.yml

Add pipenv.txt so pyup auto-updates

---

Dockerfile

Build and run locally (from reading the docs!); all's passing:
https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/stubattribution.adhoc/619/console
@davehunt r?

Switch Dockerfile image to python:2.7, from Alpine

---

.pyup.yml

@davehunt - this is just one small step to reduce in-channel bot noise, while still keeping us reasonably up-to-date.
Thoughts/r?

Schedule Pyup updates weekly, on Monday

---

Pipfile

@jrbenny35 r?
Passing ad-hoc here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/stubattribution.adhoc/878/console

Update selenium to 3.11.0 (latest)

---

.pyup.yml

Fix casing of monday, so the pyup-io bot works again

---

Jenkinsfile

Bug 1476402 - Fix cron-running logic

---

.travis.yml

Remove fte-ci@mozilla.com email from Travis
